# Generated by Django 2.1.1 on 2018-09-27 03:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
