# Generated by Django 2.1.1 on 2018-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='mypost', max_length=150),
            preserve_default=False,
        ),
    ]
